### ISSUE TITLE
Is there a way to un-register the Event?

### ISSUE THREAD

**Issue by EllisShen** [nathanbuchar/electron-settings#41]
A quick question. I'm registering a callback of "Write" event in a ReactJs component. I'm wondering is there any way to unregister it, so that I can avoid the duplicate callback when the component has been unmounted.

Like below sample code:

```
this.onWriteCallback = settings.on('write', () => {
            // doing something...
        });

ComponentWillUnmount() {
    // un-register the callback
    this.onWriteCallback();
}
```

**Comment by nathanbuchar** [comment]
ElectronSettings inherits from the native Node [`events.EventEmitter`](https://nodejs.org/api/events.html#events_class_eventemitter) class.

If you can use [`settings.once`](https://nodejs.org/api/events.html#events_emitter_once_eventname_listener), although I wouldn't recommend this because it may also negatively affect `"write"` handlers elsewhere in your code. Actually, come to think of it, the ElectronSettings internal key path observer [listens for the `"write"` event](https://github.com/nathanbuchar/electron-settings/blob/master/lib/observer.js#L65), so using `once` would probably break that (I'll fix this in a later release!)

I suggest you simply call `.removeEventListener()`, or the local alias `.off()`, like so:

```js
this.onWriteCallback = settings.on('write', handleWrite);
this.handleWrite = this.onWrite.bind(this);

ComponentWillUnmount() {
    settings.off('write', this.handleWrite);
    this.onWriteCallback();
}
```

As an aside, you should always try to pass a defined function into an event callback, instead of an anonymous one, so that you can unbind an event in the future.

Does this help? Do you have any questions? Always happy to help :)

**Comment by EllisShen** [comment]
Thank you @nathanbuchar! IT's very helpful. Sorry for my late reply.
