### ISSUE TITLE
Changes 2.x => 3.0

### ISSUE THREAD

**Issue by black-snow** [nathanbuchar/electron-settings#67]
Hey there,

thanks for pushing 3.0. Could you list the changes from 2.x to 3.0? It's a *pita* to extract the upgrade steps from the commit history.

**Comment by nathanbuchar** [comment]
Hey Ronald,

Certainly! Bare with me, the list is quite exhaustive. As a preface, in general the changes that were made were done so in order to reduce the complexity of the framework as a whole. For all intents and purposes, v3 is a drastically different and slimmer version of the same framework. Upgrading will likely not be easy, but I am available to help!

Here is what you need to know:

# Global Changes

* All methods are now synchronous.

    One of my gripes about <v3 were the technical headaches caused by asynchronous saving and promises. Not only was it Promise heavy (I honestly prefer callbacks), one common issue is that it's not unheard for a user to run `settings.set()` in two different places at the same time, and then run into conflicts and corrupted data. I suppose a solution would be to add some sort of queueing system, but that's going down quite a rabbit hole.

* Since there is no longer async saving, the `atomicSaving` option has been removed.

* The ability to customize the settings file and directory name using `configure()` has been removed. The file is now located in your app's user data path in a file called `Settings`. You can programatically change your app's user data path by using `app.setPath('userData', 'new/destination)`, but that is not recommended.

# Method Changes

## Deleted

* ### ~~`hasSync()`~~
    
    This method has been removed and replaced by `has()`.

* ### ~~`getSync()`~~
    
    This method has been removed and replaced by `get()`.

* ### ~~`deleteSync()`~~
   
    This method has been removed and replaced by `delete()`.

* ### ~~`observe()`~~
    
    This method has been removed and replaced by `watch()`.

* ### ~~`pathToSettingsFile()`~~
    
    This method has been removed and replaced by `file()`.

* ### ~~`configure()`~~
* ### ~~`applyDefaults()`~~
* ### ~~`applyDefaultsSync()`~~
* ### ~~`resetToDefaults()`~~
* ### ~~`resetToDefaultsSync()`~~
* ### ~~`settingsFileExists()`~~

## Added

* ### `getAll()`
    
    `settings.getAll():Object`

    This returns the entire settings object. Previously, this was done by calling `get()` without a first parameter.
    
    **Example**
    
    ```js
    const obj = settings.getAll();
    ```

* ### `setAll()`
    
    `settings.setAll(obj[, options])`

    This sets the entire settings object. Previously, this was done by calling `set()` without a first parameter.
    
    **Example**
    
    ```js
    settings.setAll({foo: 'bar'});
    ```

* ### `deleteAll()`
    
    `settings.deleteAll([options])`

    This deletes the entire settings object. Previously, this was done by calling `clear()` or `clearSync()`.
    
    **Example**
    
    ```js
    settings.deleteAll();
    ```

* ### `watch()`
    
    `settings.watch(keyPath, handler):Observer`

    This watches a key path for changes. This replaces `observe()` is acts exactly the same, except that instead of passing an object into the handler callback, it passed to arguments, `newValue`, and `oldValue`.
    
    **Example**
    
    ```js
    settings.watch('foo', (newValue, oldValue) => {
        // body...
    });
    ```

* ### `file()`
    
    `settings.file(keyPath, handler):string`

    This returns the absolute path to where the settings file is or will be stored. This replaces `pathToSettingsFile()`.
    
    **Example**
    
    ```js
    const settingsFilePath = settings.file();
    ```

## Changed

* ### `has()`

    **What's changed?**

    * No longer returns a Promise.   
    * No longer asynchronous.
    
    **Previously**

    `settings.has(keyPath):Promise`
    
    ```js
    settings.has('foo').then(exists => {
      console.log(exists);
    });
    ```

    **Now**
    
    `settings.has(keyPath):boolean`
    
    ```js
    const exists = settings.has(keyPath);
    
    console.log(exists);
    ```

* ### `get()`

    **Notes**

    * No longer returns a Promise.   
    * No longer asynchronous.
    * A key path must be passed in as the first parameter. Previously omitting the key path would return the entire settings object. This functionality has been replaced with `getAll()`.
    
    **Previously**

    `settings.get(keyPath):Promise`
    
    ```js
    settings.get('foo').then(value => {
        console.log(value);
    });
    ```

    **Now**
    
    `settings.get(keyPath):any`
    
    ```js
    const value = settings.get('foo');

    console.log(value);
    ```

* ### `set()`

    **Notes**

    * No longer returns a Promise.   
    * No longer asynchronous.
    * A key path must be passed in as the first parameter. Previously omitting the key path would return the entire settings object. This functionality has been replaced with `setAll()`.
    
    **Previously**

    `settings.set(keyPath, value[, options]):Promise`
    
    ```js
    settings.set('foo', 'bar').then(() => {
        // body...
    });
    ```

    **Now**
    
    `settings.set(keyPath, value[, options]):void`
    
    ```js
    settings.set('foo', 'bar');
    ```

* ### `delete()`

    **Notes**

    * No longer returns a Promise.   
    * No longer asynchronous.
    
    **Previously**

    `settings.delete(keyPath[, options]):Promise`
   
    ```js
    settings.delete('foo').then(() => {
        // body...
    });
    ```

    **Now**
    
    `settings.delete(keyPath[, options])`
    
    ```js
    settings.delete('foo');
    ```

* ### `observe()`

    Functionality is exactly the same, it has just been renamed to `watch()`.

**Comment by nathanbuchar** [comment]
Let me know if you have any other questions. Happy to help!

**Comment by black-snow** [comment]
That's quite a list, there ;)

Thank you very much for picking this together. I'll close this issue and leave it for documentation purpose. I won't get back to the last project I used the settings anytime soon but I will report back when I do.
