### ISSUE TITLE
Dont loose settings after externally editing

### ISSUE THREAD

**Issue by k7sleeper** [nathanbuchar/electron-settings#83]
If you change settings (i.e. by editor) so that the settings file does not contain valid JSON `electron-settings` empties the settings file :-(

I would appreciate `electron-settings` distinguishes parsing errors from file access errors!

**Comment by nathanbuchar** [comment]
I understand this could be frustrating, but the issue here is that electron-settings does not know how to recover so instead of throwing an error it instead fails silently. Whether you removed a single `{` or added a trailing comma, versus erasing a large chunk of the file, all electron-settings knows is that the JSON is invalid, and cannot self-correct it.

**Comment by nathanbuchar** [comment]
One solution I can think of is to store a local cache of the settings Object and if the JSON is invalid it can replace it with the cached copy instead of wiping it.

**Comment by k7sleeper** [comment]
Well, as far as I see `electron-settings` throws an exceptions if it's not able to write the settings file. Why not throw an exception if JSON parsing fails?

**Comment by nathanbuchar** [comment]
If electron-settings were to throw an error, what good would that do? From a developer's perspective, yes it may point to a problem in the Settings file, but as long the settings file is not being edited directly with the app running, then the settings file will always be valid JSON anyway. 

Especially from an end-user perspective—It would be far less jarring for data to be lost, than for an app to crash every single time the user tries to open it.

My point is whether I throw an error or not, the data is still not recoverable, so instead of crashing the app, why not just fail gracefully?

**Comment by k7sleeper** [comment]
I'm not sure whether I understood you right. My intention is to make my App fail gracefully if the settings contain invalid data.

My App only reads the settings. It's not required to change the settings by the App itself but by using an editor. If the service personal changes a setting it's required that the App do not start-up but fail with displaying a descriptive message. I would implement this by catching a JSON parsing exception.

**Comment by stavlocker** [comment]
@nathanbuchar Instead of emptying the invalid file, throwing an "invalid JSON" error and not retrieving data from settings (as there is none because the file is invalid) would be a cleaner solution.

**Comment by nathanbuchar** [comment]
Closing this as it pertains to an older version of Electron Settings. A new major release (v4) of Electron Settings was just released!
